Update git news

diff --git a/git-news b/git-news
--- a/git-news
+++ b/git-news
@@ -11,22 +11,27 @@ is_git_repo() {
 
 is_git_repo
 
-read -e -p "Enter first ref: " ref1
+ref1=$1
+ref2=$2
 
-if [ -z "${ref1}" ]; then
-  echo "Ref is required"
+if [ -z "$ref1" ]; then
+  read -e -p "Enter first ref: " ref1
+  if [ -z "$ref1" ]; then
+    echo "Ref is required"
+    exit 1
+  fi
 fi
 
-read -e -p "Enter second ref: " ref2
-
-if [ -z "${ref2}" ]; then
-  echo "Ref is required"
+if [ -z "$ref2" ]; then
+  read -e -p "Enter second ref: " ref2
+  if [ -z "$ref2" ]; then
+    echo "Ref is required"
+    exit 1
+  fi
 fi
 
-echo -e "\n"
+git_log_output=$(git --no-pager log --pretty=format:" * %s" --no-merges --no-decorate "$ref1".."$ref2")
 
-git --no-pager log --pretty=format:" * %s" --no-merges --no-decorate "$ref1".."$ref2"
-
-git --no-pager log --pretty=format:" * %s" --no-merges --no-decorate "$ref1".."$ref2"|wc -l
-
-echo -e "\n"
+if [ -n "$git_log_output" ]; then
+  echo "$git_log_output"
+fi
